export const IPC_CHANNELS = {
  APP_INFO: 'app:info',

  STORE_GET: 'store:get',
  STORE_SET: 'store:set',
  STORE_DELETE: 'store:delete',

  GIT_STATUS: 'git:status',
  GIT_LOG: 'git:log',
  GIT_DIFF: 'git:diff',
  GIT_SHOW: 'git:show',
  GIT_REV_PARSE: 'git:rev-parse',
  GIT_CLONE: 'git:clone',
  GIT_FETCH: 'git:fetch',
  GIT_PULL: 'git:pull',
  GIT_PUSH: 'git:push',
  GIT_COMMIT: 'git:commit',
  GIT_STASH: 'git:stash',
  GIT_MERGE: 'git:merge',
  GIT_REBASE: 'git:rebase',
  GIT_RESET: 'git:reset',
  GIT_REVERT: 'git:revert',
  GIT_AMEND: 'git:amend',
  GIT_CHECKOUT: 'git:checkout',
  GIT_BRANCH: 'git:branch',
  GIT_BRANCH_FIRST_PARENT: 'git:branch-first-parent',
  GIT_CURRENT_BRANCH: 'git:current-branch',
  GIT_TAG: 'git:tag',
  GIT_PATCH: 'git:patch',
  GIT_CONFIG: 'git:config',
  GIT_HOOKS: 'git:hooks',

  FS_SELECT_DIRECTORY: 'fs:select-directory',
  FS_SELECT_FILE: 'fs:select-file',
  FS_SIZE: 'fs:size',
  FS_WORKSPACE_SIZE: 'fs:workspace-size',
  FS_ICON: 'fs:icon',
  FS_WORKSPACE_LIST: 'fs:workspace-list',
  FS_WORKSPACE_CREATE: 'fs:workspace-create',
  FS_WORKSPACE_REMOVE: 'fs:workspace-remove',
  FS_DETECT_REPOS: 'fs:detect-repos',
  FS_BUILD_REPO_ID: 'fs:build-repo-id',
  FS_SCAN_REPOS: 'fs:scan-repos',
  FS_READ_IMAGE_DATA_URL: 'fs:read-image-data-url',

  AUTH_GITHUB_START: 'auth:github-start',
  AUTH_GITHUB_COMPLETE: 'auth:github-complete',
  AUTH_GITLAB_START: 'auth:gitlab-start',
  AUTH_GITLAB_COMPLETE: 'auth:gitlab-complete',
  ACCOUNT_LIST: 'account:list',
  ACCOUNT_SET_ACTIVE: 'account:set-active',
  ACCOUNT_REMOVE: 'account:remove',

  GITHUB_LIST_REPOS: 'github:list-repos',
  GITLAB_LIST_REPOS: 'gitlab:list-repos',

  SHELL_OPEN_TERMINAL: 'shell:open-terminal',
  SHELL_OPEN_FINDER: 'shell:open-finder'
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
